services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    hostname: kafka

    ports:
      - "9092:9092"
      - "29092:29092"
      - "29093:29093"

    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      # ---- KRaft ----
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      # ---- Listeners ----
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_LISTENERS: >
        PLAINTEXT_HOST://0.0.0.0:9092,
        PLAINTEXT://kafka:29092,
        CONTROLLER://kafka:29093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT_HOST://localhost:9092,
        PLAINTEXT://kafka:29092

      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # ---- Storage ----
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

      # ---- RTTM safety ----
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      # ---- Single node ----
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      CLUSTER_ID: "C-1Pn8WSTOamp-3aPkhjGQ"

    command: >
      bash -c "
        /etc/confluent/docker/run &

        echo 'Waiting for Kafka broker...';
        until kafka-broker-api-versions --bootstrap-server kafka:29092 > /dev/null 2>&1; do
          sleep 2;
        done;

        echo 'Creating RTTM topics...';

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.trade.events --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.queue.metrics --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.error.events --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.dlq.events --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.service.heartbeat --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.alert.events --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic invalid-trades-topic --partitions 2 --replication-factor 1;

        echo 'Kafka ready.';
        wait
      "

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"


  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      
volumes:
  kafka-data:
  redis-data:
