services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    hostname: kafka

    ports:
      - "9092:9092"
      - "29092:29092"
      - "29093:29093"

    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      # ---- KRaft ----
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      # ---- Listeners ----
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_LISTENERS: >
        PLAINTEXT_HOST://0.0.0.0:9092,
        PLAINTEXT://kafka:29092,
        CONTROLLER://kafka:29093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT_HOST://localhost:9092,
        PLAINTEXT://kafka:29092

      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # ---- Storage ----
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

      # ---- RTTM safety ----
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      # ---- Single node ----
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      CLUSTER_ID: "C-1Pn8WSTOamp-3aPkhjGQ"

    command: >
      bash -c "
        /etc/confluent/docker/run &

        echo 'Waiting for Kafka broker...';
        until kafka-broker-api-versions --bootstrap-server kafka:29092 > /dev/null 2>&1; do
          sleep 2;
        done;

        echo 'Creating RTTM topics...';

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.trade.events --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.queue.metrics --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.error.events --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.dlq.events --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.service.heartbeat --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rttm.alert.events --partitions 2 --replication-factor 1;

        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic invalid-trades-topic --partitions 2 --replication-factor 1;

        echo 'Kafka ready.';
        wait
      "

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"

  redis-master:
    image: redis:7.4
    container_name: redis-master
    hostname: redis-master
    command: redis-server /redis/redis-master.conf
    volumes:
      - ./redis:/redis
      - redis-master-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis-replica-1:
    image: redis:7.4
    container_name: redis-replica-1
    hostname: redis-replica-1
    command: redis-server /redis/redis-replica.conf
    volumes:
      - ./redis:/redis
      - redis-replica-1-data:/data
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-replica-2:
    image: redis:7.4
    container_name: redis-replica-2
    hostname: redis-replica-2
    command: redis-server /redis/redis-replica.conf
    volumes:
      - ./redis:/redis
      - redis-replica-2-data:/data
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  sentinel-1:
    image: redis:7.4
    container_name: sentinel-1
    hostname: sentinel-1
    command: redis-sentinel /redis/sentinel-1.conf
    volumes:
      - ./redis:/redis
      - sentinel-1-data:/data
    depends_on:
      redis-master:
        condition: service_healthy
    ports:
      - "26379:26379"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  sentinel-2:
    image: redis:7.4
    container_name: sentinel-2
    hostname: sentinel-2
    command: redis-sentinel /redis/sentinel-2.conf
    volumes:
      - ./redis:/redis
      - sentinel-2-data:/data
    depends_on:
      redis-master:
        condition: service_healthy
    ports:
      - "26380:26379"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  sentinel-3:
    image: redis:7.4
    container_name: sentinel-3
    hostname: sentinel-3
    command: redis-sentinel /redis/sentinel-3.conf
    volumes:
      - ./redis:/redis
      - sentinel-3-data:/data
    depends_on:
      redis-master:
        condition: service_healthy
    ports:
      - "26381:26379"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  kafka-data:
  redis-master-data:
  redis-replica-1-data:
  redis-replica-2-data:
  sentinel-1-data:
  sentinel-2-data:
  sentinel-3-data:
